language: julia
notifications:
    email: false
julia:
    - 0.7
    - 1.0
    - 1.1
    - nightly
after_success:
    - julia -e 'cd(Pkg.dir("DCEMRI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

